github: hocram
open_collective: unicoverso
patreon: UnicoVerso
ko_fi: marcodipasquale
custom:
  - "https://unicoverso.com/dona"
  - "https://paypal.me/marcodipasquale"
  - "https://www.buymeacoffee.com/hocram"
